### ISSUE TITLE
Añadir al menos 2 objetivos más

### ISSUE THREAD

**Issue by adrianeguez** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#1]
Hola, quisiera saber si pueden añadir dos objetivos más a su proyecto, no lo encuentro muy claro

**Comment by OscarLoor** [comment]
Buenos puedes encontrar la información actualizada en el link: https://github.com/AppLibresPruebaGUI/App_Libres_Prueba_GUI/blob/master/README.md
