### ISSUE TITLE
Lista de Suscriptores

### ISSUE THREAD

**Issue by OscarLoor** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#11]
Tenemos que buscar el gestor para las listas de suscriptores

**Comment by OscarLoor** [comment]
Compañeros propongo relizar la lista de suscriptores con mailchimp, este nos genera formularios HTML los cuales se enlazan directamente con la cuenta, y la creación de mails se realiza con plantillas ya realizadas o con una propia, es gratis hasta 2000 suscriptores y me parece que para empezar esta muy bien, si desean pueden ver información detallada sobre precios en: http://mailchimp.com/pricing/entrepreneur/

@FreddyBazante @StanGumn @f3ar161 @juanfcreyes

**Comment by juanfcreyes** [comment]
Gracias @OscarLoor por la implementación de la lista, realmente colaboras bastante con nosotros y el proyecto
