### ISSUE TITLE
Correos de gmail

### ISSUE THREAD

**Issue by FreddyBazante** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#12]
Se necesita los correos de gmail para poder empezar con el diseno de interfaces en drive y asi realizarlo de manera colaborativa

**Comment by OscarLoor** [comment]
Mi mail es: loor.oscar2012@gmail.com y el de hotmail dwquito@hotmail.com

**Comment by juanfcreyes** [comment]
boikotsocial@gmail,com

**Comment by juanfcreyes** [comment]
boikotsocial@hotmail.com

**Comment by CarlosEd91** [comment]
carlos.e.sampedro.91@gmail.com

**Comment by juanfcreyes** [comment]
Esto ya no es necesario, puesto que el sieño lo realizamos en clases.
