### ISSUE TITLE
Modificación de Información en la Wiki y Página Web

### ISSUE THREAD

**Issue by OscarLoor** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#14]
Compañeros realice un cambio en el archivo README.md, con las nuevas especificaciones realizadas el día 2015/10/14, por favor alguien realice el cambio en la Wiki y Página Web con la nueva información.

**Comment by OscarLoor** [comment]
@CarlosEd91 @FreddyBazante @StanGumn @f3ar161

**Comment by StanGumn** [comment]
Se edito y modificó la página web y wiki por parte de los integrantes del grupo
