### ISSUE TITLE
No hay nada en el wiki

### ISSUE THREAD

**Issue by adrianeguez** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#2]
Hola, no encontré nada de información en el Wiki, por favor actualicen la información pertinente

**Comment by OscarLoor** [comment]
Buenos días el link de la wiki ya se encuentra actualizado: https://github.com/AppLibresPruebaGUI/App_Libres_Prueba_GUI/wiki/Wiki-Pruebas-Gui
