### ISSUE TITLE
Links Web y Wiki no disponibles

### ISSUE THREAD

**Issue by adrianeguez** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#3]
Hola, no encuentro los links a su pagina Web y Wiki, por favor arreglen esto

**Comment by OscarLoor** [comment]
Buenos días los links son los siguientes:

Wiki: https://github.com/AppLibresPruebaGUI/App_Libres_Prueba_GUI/wiki/Wiki-Pruebas-Gui
Página Web: http://applibrespruebagui.github.io/App_Libres_Prueba_GUI/
