### ISSUE TITLE
Tanto en la página Web, como en el Wiki deben de tener el prototipo de la interfaz con la  navegación. 

### ISSUE THREAD

**Issue by OscarLoor** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#30]

**Comment by juanfcreyes** [comment]
Muchachos he creado una nueva rama(branch) llamada maquetación, donde existe una carpeta llamada maqueta, en esta suban las imagenes que corresponden el prototipo de la interfaz. 
El último en subir su imagen correpondiente realice un pull request, para integrar el prototipado en la rama principal y de por cerrado este issue
