### ISSUE TITLE
Dividir Trabajo

### ISSUE THREAD

**Issue by OscarLoor** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#31]
Muchachos yo me encargo de la página web, ustedes realicen los cambios en los otros campos, lo que también falta es el prototipo de la interfaz de navegación les recomiendo que lo realicen en: http://webdemo.balsamiq.com/, esta versión solo permite editar por una hora, despues pueden tomar una foto de pantalla, les adjunto un documento que realice con los contenidos adicionales que deberían tener los entregables https://www.dropbox.com/s/uk79krfzywlwrg0/AplicacionesEnAmbientesLibres.docx?dl=0

**Comment by OscarLoor** [comment]
Para la suscripción en MailChimp se crearon dos cuentas los accesos los agrego aqui:

Mailchimp:
UserName: PruebasGUI
Contraseña: 1Pruebas2gui@

Hotmail:
Email: pruebasgui@hotmail.com
Contraseña: 1Pruebas2gui

**Comment by juanfcreyes** [comment]
Muchachos aquí esta la asignación de las tareas que ha cada uno le corresponde realizar.
Tareas 
1.  SAN PEDRO Los colaboradores deben de estar tanto en el Wiki como en la página Web y el Readme.
2.  JUAN Deben de escribir el estado del proyecto (en desarrollo por ejemplo) Wiki como en la página Web y el Readme
3.  ANGEL Guía de como suscribirse al proyecto.
4.  SAN PEDRO Qué tipo de suscripciones hay y cuáles serían sus roles.
5.  SAN PEDRO Describir cada uno de los labels, como utilizarlos para los colaboradores.
6.  FREDDY Cambiar los objetivos a los actuales (ya no es mediante archivos JSON sino se puede conectar con cualquier base de datos – mysql, postgresql, Oracle, mssql, mongodb, etc).
7.  JUAN Mediante los Issues es cómo  se debe de comunicar el grupo, debe de haber evidencia del trabajo y la coordinación que han tenido mediante esto.
8.  STALIN En los Issues escribir las características que se han ido desarrollando durante este bimestre y asignarles a un Milestone llamado “1er Biemstre”.
9.  FREDDY Label que estén en español y sean usados algunos de ellos.
10. ANGEL Usar los “pull request” para hacer los cambios en la Página Web.
11. STALIN No debe de haber ningún issue “Abierto”.
12. ANGEL Tanto en la página Web, como en el Wiki deben de tener el prototipo de la interfaz con la navegación.

**Comment by StanGumn** [comment]
De igual forma las interfaces prototipo se realizo en grupo y cada uno sube el prototipo
