### ISSUE TITLE
Me podrían decir que base de datos usamos? Por favor

### ISSUE THREAD

**Issue by FreddyBazante** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#34]

**Comment by OscarLoor** [comment]
Esta en este link si buscas la estructura: https://github.com/AppLibres2015b/App_Libres_2015_b/blob/master/Base.xlsx?raw=true, si era el tipo de base de datos es PostgreSQL en Heroku y los datos para la conexión son: https://www.dropbox.com/s/bzi14691lrde5s6/String%20de%20Conexion-Heroku.txt?dl=0
