### ISSUE TITLE
Votar por licencia

### ISSUE THREAD

**Issue by CarlosEd91** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#43]

**Comment by OscarLoor** [comment]
A mi forma de ver la licencia MIT nos permitirá atraer a más usuarios

**Comment by CarlosEd91** [comment]
Resultados de la votación: 
![eleccionlicencia](https://cloud.githubusercontent.com/assets/15015065/12970250/42821fd2-d05a-11e5-98bb-52e047987bfe.PNG)
