### ISSUE TITLE
Se requiere información!

### ISSUE THREAD

**Issue by juanfcreyes** [AppLibresPruebaGUI/App_Libres_Prueba_GUI#8]
Disculpen muchahos no se si me podrían brindar información detallada de lo que trata todo el proyecto en general. Además de informarme acerca de ¿Qué nos hace falta?, para empezar a aportar.

**Comment by OscarLoor** [comment]
Hola Juan, acabe de modificar la información del proyecto https://github.com/AppLibresPruebaGUI/App_Libres_Prueba_GUI/blob/master/README.md, me parece que ahora esta mucho más especificada nuestra labor, trata siempre de comentar los ISSUES aqui agregaremos las tareas pendientes y tambien por que cada clase se realiza una revisión con las modificaciones del proyecto, comentarios, etc.

**Comment by juanfcreyes** [comment]
Muchas gracias Oscar
